import Foundation

/// Generates self-contained HTML documents from session data.
/// Output includes a dark-mode stylesheet and is compatible with
/// Notion, Obsidian, and standard browser rendering.
struct HTMLExporter {
    static let shared = HTMLExporter()
    private init() {}

    func generateHTML(session: Session, segments: [Segment]) -> String {
        let date   = session.startTime.formatted(date: .long, time: .shortened)
        let dur    = session.formattedDuration
        let export = Date().formatted(date: .long, time: .shortened)
        let rows   = renderTranscript(segments)

        return """
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>FlowDoc – \(esc(date))</title>
        <style>
        body{font-family:-apple-system,BlinkMacSystemFont,'SF Pro Display','Segoe UI',sans-serif;max-width:780px;margin:0 auto;padding:32px 24px;color:#13343B;line-height:1.6;background:#FCFCF9}
        h1{font-size:26px;font-weight:600;margin-bottom:4px}
        h2{font-size:18px;font-weight:600;color:#21808D;margin-top:32px;margin-bottom:10px;border-bottom:1px solid #E8E8E4;padding-bottom:6px}
        .summary{background:#F5F5F0;border-radius:10px;padding:16px 20px;margin-top:12px}
        .summary p{margin:4px 0;font-size:14px}.summary b{color:#13343B}
        .ts{color:#21808D;font-weight:600;font-size:13px;font-variant-numeric:tabular-nums}
        .transcript p{margin:6px 0}
        .pause{color:#A84B2F;font-style:italic;font-size:13px;background:#FFF5F0;display:inline-block;padding:4px 10px;border-radius:4px;margin:8px 0}
        .footer{margin-top:40px;padding-top:14px;border-top:1px solid #E8E8E4;font-size:12px;color:#A7A9A9}
        @media(prefers-color-scheme:dark){body{background:#1F2121;color:#F5F5F5}.summary{background:#262828}h2{color:#32B8C6;border-bottom-color:#2C2E2E}.ts{color:#32B8C6}.pause{background:#2C2E2E;color:#E68161}.footer{border-top-color:#2C2E2E;color:#77787C}}
        </style>
        </head>
        <body>
        <h1>🎙️ FlowDoc Session</h1>
        <div class="summary">
        <p><b>Date</b>&nbsp;&nbsp;\(esc(date))</p>
        <p><b>Duration</b>&nbsp;&nbsp;\(esc(dur))</p>
        </div>
        <h2>📝 Transcript</h2>
        <div class="transcript">
        \(rows)
        </div>
        <div class="footer">Generated by FlowDoc · \(esc(export))</div>
        </body>
        </html>
        """
    }

    // MARK: – Private

    private func renderTranscript(_ segments: [Segment]) -> String {
        guard !segments.isEmpty else {
            return "<p><em>No transcript recorded.</em></p>"
        }
        return segments.map { seg in
            let spk = seg.speakerID.map { "Speaker \($0): " } ?? ""
            return "<p><span class=\"ts\">[\(seg.formattedTimestamp)]</span> \(spk)\(esc(seg.text))</p>"
        }.joined(separator: "\n")
    }

    private func esc(_ s: String) -> String {
        s.replacingOccurrences(of: "&",  with: "&amp;")
         .replacingOccurrences(of: "<",  with: "&lt;")
         .replacingOccurrences(of: ">",  with: "&gt;")
         .replacingOccurrences(of: "\"", with: "&quot;")
    }
}
